name: Workflow 备份仓库         # 显示在 Actions 页面的名字

on:                          # 触发条件
  workflow_dispatch:         # 手动触发
  push:                      # 推送时触发
    branches: [main]
  schedule:                  # 定时触发
    - cron: '0 0 * * 0'

jobs:
  build:                     # 任务ID
    runs-on: ubuntu-22.04    # 运行环境
    steps:
      - name: 备份仓库
        run: |
          echo "执行命令"
