#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/openwrt-builder.yml
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
name: 编译 Build OneCloud 测试
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH连接到Actions环境 | SSH connection to Actions'
        required: false
        default: 'false'
  schedule:
    - cron: '0 1 10 * *'
env:
  REPO_URL: https://github.com/openwrt/openwrt.git
  REPO_BRANCH: openwrt-24.10
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: onecloud.config
  DIY_P1_SH: op1.sh
  DIY_P2_SH: op2.sh
  DIY_P3_SH: op3.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: false
  TZ: Asia/Shanghai
jobs:
  build:
    name: 编译任务 build
    runs-on: ubuntu-22.04
    steps:
    - name: 拉取本仓库代码
      uses: actions/checkout@v4
    - name: 初始化编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo docker image prune -a
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build‑essential bzip2 cmake cpio curl devscripts diffstat flex g++ gawk gettext git gperf libncurses‑dev libssl‑dev m4 make nano ncurses‑term pkg‑config python3‑python‑dotenv rsync scons sed unzip wget zlib1g‑dev
    - name: 克隆OpenWrt源码
      working‑directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL openwrt
        cd openwrt
        git checkout $REPO_BRANCH
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
    - name: 导入配置文件
      run: |
        [ -e $CONFIG_FILE ] && cp $CONFIG_FILE openwrt/.config
        [ -e $FEEDS_CONF ] && cp $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $GITHUB_WORKSPACE/$DIY_P1_SH $GITHUB_WORKSPACE/$DIY_P2_SH $GITHUB_WORKSPACE/$DIY_P3_SH
    - name: 执行DIY脚本1
      run: |
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH
    - name: 更新feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: 执行DIY脚本2
      run: |
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH
    - name: SSH远程调试连接
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    - name: 预下载全部源码包
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    - name: 编译固件
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        if ! make -j$(nproc); then
            echo "make -j1 V=s retry..."
            make -j1 V=s
        fi
        echo "status=success" >> $GITHUB_OUTPUT
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_OUTPUT
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_OUTPUT
    - name: 生成晶晨线刷镜像
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        chmod +x $GITHUB_WORKSPACE/Scripts/convert2.sh
        $GITHUB_WORKSPACE/Scripts/convert2.sh
    - name: 查看磁盘空间
      if: (!cancelled())
      run: df -hT
    - name: 上传bin目录工件
      uses: actions/upload-artifact@v4
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: openwrt_bin${{ steps.compile.outputs.FILE_DATE }}
        path: openwrt/bin
    - name: 上传固件工件
      uses: actions/upload-artifact@v4
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true'
      with:
        name: openwrt_firmware${{ steps.compile.outputs.FILE_DATE }}
        path: openwrt/bin/targets
    - name: 生成Release信息
      id: tag
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true'
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")${{ steps.compile.outputs.DEVICE_NAME }}" >> $GITHUB_OUTPUT
        echo "status=success" >> $GITHUB_OUTPUT
    - name: 发布到Github Release
      uses: softprops/action-gh-release@v2
      if: steps.tag.outputs.status == 'success'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        name: OpenWrt ${{ steps.compile.outputs.FILE_DATE }}
        files: openwrt/bin/targets/**/*
    - name: 清理旧Workflow运行记录
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 7
        keep_minimum_runs: 2
    - name: 删除旧Release版本
      if: env.UPLOAD_RELEASE == 'true' && steps.compile.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        RELEASE_TAGS=$(gh release list --json tagName,publishedAt --order desc | jq -r '.[5:] | .[].tagName')
        for TAG in $RELEASE_TAGS; do
          echo "删除旧Release: $TAG"
          gh release delete "$TAG" -y
        done
